"""PX4 SITL launch with REAL VISION from a Gazebo camera + moving red ball.

Replaces the fake_detection_node from sitl_mission_launch.py with:
  1. ros_gz_bridge — bridges the Gazebo camera sensor + set_pose service
  2. gz_cam_republisher — compresses Gazebo images onto the standard
     /drone/camera/image_raw/compressed topic
  3. red_ball spawn — drops a 0.2 m red sphere into the running world
  4. target_mover_node — orbits the ball in a circle via SetEntityPose
  5. yolo_node — runs YOLO inference on the compressed stream
  6. detection_gate_node — validates detections (same as real-hardware path)
  7. heartbeat_node — ground-station heartbeat for the watchdog

Everything else (tracker, control, mission executor, telemetry, dashboard)
runs identically to the real split-architecture stack.

Gazebo camera topic:
  PX4 SITL models publish camera images via Gazebo transport. The default
  matches the x500_mono_cam model in the "default" world (PX4 appends _0):
    /world/default/model/x500_mono_cam_0/link/camera_link/sensor/camera/image

  Override gz_camera_topic:= and gz_world_name:= if your setup differs.

Usage (after PX4 SITL + Gazebo are running):
  scripts/ros_wsl.sh gazebo
  scripts/ros_wsl.sh gazebo device:=cuda:0 model_path:=red_ball_yolo26s.pt

Split setup (gz on a separate PC, e.g. a 5080):
  # On the sim PC (renders + owns the ball, publishes /sim/camera/image_raw):
  scripts/ros_wsl.sh gazebo            # local_sim defaults true
  # On the laptop (consumes the feed over the LAN, runs YOLO + the stack):
  scripts/ros_wsl.sh gazebo local_sim:=false device:=cuda:0 \
      model_path:=red_ball_yolo26s.pt connection_url:=udp://<sim-pc-ip>:14540
  # Both machines: same ROS_DOMAIN_ID + RMW_IMPLEMENTATION on the same LAN.
"""

import os
import tempfile

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import (
    DeclareLaunchArgument,
    ExecuteProcess,
    LogInfo,
    OpaqueFunction,
    TimerAction,
)
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue


def _resolve_default_plan():
    try:
        share = get_package_share_directory("drone_control")
        return os.path.join(share, "missions", "scan_and_orbit.yaml")
    except Exception:
        return ""


def _resolve_ball_sdf():
    """Find red_ball.sdf shipped with this repo."""
    # Installed share path (colcon install)
    try:
        share = get_package_share_directory("dronetrack_perception")
        candidate = os.path.join(share, "models", "red_ball.sdf")
        if os.path.isfile(candidate):
            return candidate
    except Exception:
        pass
    # Dev path (symlink-install / source tree)
    here = os.path.dirname(os.path.abspath(__file__))
    for rel in [
        "../../../../models/red_ball.sdf",              # from launch/ in src tree
        "../../../models/red_ball.sdf",                  # from install share
    ]:
        candidate = os.path.normpath(os.path.join(here, rel))
        if os.path.isfile(candidate):
            return candidate
    return ""


def _create_bridge_and_spawn(context, *args, **kwargs):
    """OpaqueFunction: resolve substitutions, write bridge YAML, return nodes."""
    # SPLIT: on the laptop consumer (local_sim:=false) the 5080 owns the camera
    # bridge, the set_pose service bridge, and the ball spawn — skip them here.
    if LaunchConfiguration("local_sim").perform(context).lower() != "true":
        return []
    world = LaunchConfiguration("gz_world_name").perform(context)
    cam_gz = LaunchConfiguration("gz_camera_topic").perform(context)
    cam_ros = LaunchConfiguration("gz_ros_image_topic").perform(context)
    ball_sdf = LaunchConfiguration("ball_sdf").perform(context)
    spawn_ball = LaunchConfiguration("spawn_ball").perform(context).lower() == "true"

    # ---- write bridge config ----
    bridge_yaml = tempfile.NamedTemporaryFile(
        mode="w", suffix=".yaml", prefix="gz_bridge_", delete=False
    )
    bridge_yaml.write(
        f"# Auto-generated by sitl_gazebo_launch.py\n"
        f"- ros_topic_name: \"{cam_ros}\"\n"
        f"  gz_topic_name: \"{cam_gz}\"\n"
        f"  ros_type_name: \"sensor_msgs/msg/Image\"\n"
        f"  gz_type_name: \"gz.msgs.Image\"\n"
        f"  direction: GZ_TO_ROS\n"
        f"\n"
        f"- service_name: \"/world/{world}/set_pose\"\n"
        f"  ros_type_name: \"ros_gz_interfaces/srv/SetEntityPose\"\n"
        f"  gz_req_type_name: \"gz.msgs.Pose\"\n"
        f"  gz_rep_type_name: \"gz.msgs.Boolean\"\n"
        f"  direction: ROS_TO_GZ\n"
    )
    bridge_yaml.flush()
    config_path = bridge_yaml.name
    bridge_yaml.close()

    actions = []

    # ---- ros_gz_bridge (camera topic + set_pose service) ----
    actions.append(Node(
        package="ros_gz_bridge",
        executable="parameter_bridge",
        name="gz_bridge",
        parameters=[{"config_file": config_path}],
        output="screen",
    ))

    # ---- spawn red ball (delayed 2 s so the bridge is up) ----
    if spawn_ball and ball_sdf and os.path.isfile(ball_sdf):
        actions.append(TimerAction(
            period=2.0,
            actions=[
                LogInfo(msg=["Spawning red_ball from ", ball_sdf]),
                ExecuteProcess(
                    cmd=[
                        "ros2", "run", "ros_gz_sim", "create",
                        "-name", "red_ball",
                        "-file", ball_sdf,
                        "-x", "5", "-y", "0", "-z", "1",
                        "-world", world,
                    ],
                    output="screen",
                ),
            ],
        ))
    elif spawn_ball:
        actions.append(LogInfo(
            msg=f"WARNING: red_ball.sdf not found at '{ball_sdf}'. "
                "Spawn manually or set ball_sdf:= to the correct path."
        ))

    return actions


def generate_launch_description() -> LaunchDescription:
    pi_share = get_package_share_directory("dronetrack_pi")
    gs_share = get_package_share_directory("dronetrack_groundstation")
    default_pi_params = os.path.join(pi_share, "config", "pi.yaml")
    default_gs_params = os.path.join(gs_share, "config", "groundstation.yaml")
    default_plan = _resolve_default_plan()
    default_ball_sdf = _resolve_ball_sdf()

    # ---- Launch arguments ----
    args = [
        DeclareLaunchArgument("params_file", default_value=default_pi_params,
                              description="Pi-side params YAML."),
        DeclareLaunchArgument("gs_params_file", default_value=default_gs_params,
                              description="Ground-station params YAML."),
        DeclareLaunchArgument("mission_plan_file", default_value=default_plan,
                              description="Mission YAML for mission_executor_node."),
        DeclareLaunchArgument("connection_url", default_value="udp://:14540",
                              description="MAVSDK connection URL for PX4 SITL."),
        DeclareLaunchArgument("allow_mavsdk_actions", default_value="true",
                              description="SITL: allow TAKEOFF/ORBIT/LAND actions."),
        DeclareLaunchArgument("allow_translation_commands", default_value="false",
                              description="SITL: allow velocity/translation commands."),
        DeclareLaunchArgument("enable_approach_translation", default_value="false",
                              description="Let control_node generate forward approach velocity."),
        DeclareLaunchArgument("allow_scan_without_lock", default_value="false",
                              description="Allow yaw-only SCAN while target is not locked."),
        DeclareLaunchArgument("auto_start", default_value="false",
                              description="Start mission immediately."),
        DeclareLaunchArgument("target_class", default_value="red_ball",
                              description="YOLO target class filter."),
        DeclareLaunchArgument("dashboard", default_value="true",
                              description="Run the web dashboard."),
        DeclareLaunchArgument("dashboard_port", default_value="8091",
                              description="HTTP port for the SITL dashboard."),

        # Gazebo
        DeclareLaunchArgument(
            "gz_world_name", default_value="default",
            description="Gazebo world name (used for service bridging and ball spawn)."),
        DeclareLaunchArgument(
            "gz_camera_topic",
            default_value="/world/default/model/x500_mono_cam_0/link/camera_link/sensor/camera/image",
            description="Gazebo transport camera topic."),
        DeclareLaunchArgument(
            "gz_ros_image_topic", default_value="/sim/camera/image_raw",
            description="ROS 2 topic for the bridged Gazebo camera."),
        DeclareLaunchArgument(
            "spawn_ball", default_value="true",
            description="Spawn the red ball into the Gazebo world."),
        DeclareLaunchArgument(
            "ball_sdf", default_value=default_ball_sdf,
            description="Path to the red_ball.sdf model file."),
        DeclareLaunchArgument(
            "local_sim", default_value="true",
            description="True: this machine runs gz, so it owns the camera/set_pose "
                        "bridge, the red_ball spawn, and target_mover. SPLIT setup: set "
                        "false on the laptop consumer — the 5080 publishes "
                        "/sim/camera/image_raw over the LAN and owns the ball; the laptop "
                        "only republishes + runs YOLO + the mission stack."),

        # Target mover
        DeclareLaunchArgument("ball_center_x", default_value="5.0",
                              description="Ball orbit center X (m, NED)."),
        DeclareLaunchArgument("ball_center_y", default_value="0.0",
                              description="Ball orbit center Y."),
        DeclareLaunchArgument("ball_altitude", default_value="1.0",
                              description="Ball altitude (m)."),
        DeclareLaunchArgument("ball_radius", default_value="3.0",
                              description="Ball orbit radius (m)."),
        DeclareLaunchArgument("ball_period", default_value="20.0",
                              description="Ball orbit period (s)."),

        # YOLO
        DeclareLaunchArgument("model_path", default_value="yolov8n.pt",
                              description="YOLO model path."),
        DeclareLaunchArgument("device", default_value="cpu",
                              description="YOLO device: cpu, cuda:0, mps."),
        DeclareLaunchArgument("half_precision", default_value="false",
                              description="FP16 inference (use with cuda)."),
        DeclareLaunchArgument("max_fps", default_value="15.0",
                              description="Max YOLO processing FPS."),
    ]

    params = LaunchConfiguration("params_file")
    gs_params = LaunchConfiguration("gs_params_file")

    # ---- gz_cam_republisher: raw Gazebo → compressed ----
    gz_cam_republisher = Node(
        package="dronetrack_perception",
        executable="gz_cam_republisher",
        name="gz_cam_republisher",
        parameters=[{
            "gz_image_topic": LaunchConfiguration("gz_ros_image_topic"),
            "compressed_out_topic": "/drone/camera/image_raw/compressed",
            "raw_out_topic": "/drone/camera/image_raw",
            "republish_raw": True,
            "jpeg_quality": 80,
        }],
        output="screen",
    )

    # ---- target mover: orbits the red ball (producer/local_sim side only) ----
    target_mover = Node(
        package="dronetrack_perception",
        executable="target_mover_node",
        name="target_mover_node",
        parameters=[{
            "world_name": LaunchConfiguration("gz_world_name"),
            "entity_name": "red_ball",
            "center_x": ParameterValue(LaunchConfiguration("ball_center_x"), value_type=float),
            "center_y": ParameterValue(LaunchConfiguration("ball_center_y"), value_type=float),
            "altitude": ParameterValue(LaunchConfiguration("ball_altitude"), value_type=float),
            "radius": ParameterValue(LaunchConfiguration("ball_radius"), value_type=float),
            "period_s": ParameterValue(LaunchConfiguration("ball_period"), value_type=float),
            "rate_hz": 20.0,
        }],
        output="screen",
        condition=IfCondition(LaunchConfiguration("local_sim")),
    )

    # ---- YOLO ----
    yolo = Node(
        package="dronetrack_perception",
        executable="yolo_node",
        name="yolo_node",
        parameters=[gs_params, {
            "model_path": LaunchConfiguration("model_path"),
            "target_class": LaunchConfiguration("target_class"),
            "device": LaunchConfiguration("device"),
            "half_precision": ParameterValue(LaunchConfiguration("half_precision"), value_type=bool),
            "max_fps": ParameterValue(LaunchConfiguration("max_fps"), value_type=float),
        }],
        output="screen",
    )

    # ---- Detection gate ----
    detection_gate = Node(
        package="dronetrack_pi",
        executable="detection_gate_node",
        name="detection_gate_node",
        parameters=[params, {"require_heartbeat": True}],
        output="screen",
    )

    # ---- Heartbeat ----
    heartbeat = Node(
        package="dronetrack_groundstation",
        executable="heartbeat_node",
        name="groundstation_heartbeat_node",
        parameters=[gs_params],
        output="screen",
    )

    # ---- Pi-side mission stack ----
    telemetry = Node(
        package="drone_telemetry",
        executable="telemetry_node",
        name="telemetry_node",
        parameters=[params, {
            "connection_url": LaunchConfiguration("connection_url"),
            "allow_mavsdk_actions": ParameterValue(LaunchConfiguration("allow_mavsdk_actions"), value_type=bool),
            "allow_translation_commands": ParameterValue(LaunchConfiguration("allow_translation_commands"), value_type=bool),
        }],
        output="screen", emulate_tty=True,
    )

    tracker = Node(
        package="drone_tracker",
        executable="tracker_node",
        name="tracker_node",
        parameters=[params, {"target_class": LaunchConfiguration("target_class")}],
        output="screen", emulate_tty=True,
    )

    autonomy_manager = Node(
        package="drone_control",
        executable="autonomy_manager_node",
        name="autonomy_manager_node",
        parameters=[params, {
            "allow_scan_without_lock": ParameterValue(LaunchConfiguration("allow_scan_without_lock"), value_type=bool),
        }],
        output="screen", emulate_tty=True,
    )

    control = Node(
        package="drone_control",
        executable="control_node",
        name="control_node",
        parameters=[params, {
            "enable_approach_translation": ParameterValue(LaunchConfiguration("enable_approach_translation"), value_type=bool),
        }],
        output="screen", emulate_tty=True,
    )

    mission_executor = Node(
        package="drone_control",
        executable="mission_executor_node",
        name="mission_executor_node",
        parameters=[params, {
            "mission_enabled": True,
            "auto_start": ParameterValue(LaunchConfiguration("auto_start"), value_type=bool),
            "mission_plan_file": LaunchConfiguration("mission_plan_file"),
            "require_distance_for_orbit": False,
            "require_target_centered_for_orbit": False,
        }],
        output="screen", emulate_tty=True,
    )

    health = Node(
        package="drone_diagnostics",
        executable="health_monitor_node",
        name="health_monitor_node",
        parameters=[params],
        output="screen", emulate_tty=True,
    )

    ground_station_watchdog = Node(
        package="dronetrack_pi",
        executable="ground_station_watchdog_node",
        name="ground_station_watchdog_node",
        parameters=[params],
        output="screen",
    )

    dashboard = Node(
        package="dronetrack_web_bridge",
        executable="web_dashboard_node",
        name="web_dashboard_node",
        parameters=[gs_params, {"port": ParameterValue(LaunchConfiguration("dashboard_port"), value_type=int)}],
        output="screen", emulate_tty=True,
        condition=IfCondition(LaunchConfiguration("dashboard")),
    )

    return LaunchDescription([
        *args,

        LogInfo(msg="=== DRONETRACK GAZEBO SITL — REAL VISION + RED BALL ==="),
        LogInfo(msg="Gazebo camera → YOLO → detection gate → tracker → control → PX4"),
        LogInfo(msg=["Dashboard: http://127.0.0.1:", LaunchConfiguration("dashboard_port"), "/"]),
        LogInfo(msg=["PX4 connection: ", LaunchConfiguration("connection_url")]),
        LogInfo(msg=["YOLO: ", LaunchConfiguration("model_path"), " on ", LaunchConfiguration("device"),
                      " target_class=", LaunchConfiguration("target_class")]),
        LogInfo(msg=["Gazebo world: ", LaunchConfiguration("gz_world_name"),
                      " camera: ", LaunchConfiguration("gz_camera_topic")]),
        LogInfo(msg=["Red ball orbit: r=", LaunchConfiguration("ball_radius"),
                      "m, period=", LaunchConfiguration("ball_period"), "s"]),

        # OpaqueFunction writes the bridge config and spawns the ball
        OpaqueFunction(function=_create_bridge_and_spawn),

        gz_cam_republisher,
        target_mover,
        yolo,
        heartbeat,
        detection_gate,
        ground_station_watchdog,
        telemetry,
        tracker,
        autonomy_manager,
        control,
        mission_executor,
        health,
        dashboard,
    ])
